#!/usr/bin/python
# -*- coding: utf-8 -*-

#needed to allow access to cli tools for E2guardian
import os

#imports Glade GTK library
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk

#defines Handlers
class Handler:
    def onDestroy(self, *args):
        Gtk.main_quit()
    def e2g_start(self, button):
        os.system("service e2guardian start")
        start = builder.get_object("start")
        start.set_text("Started")
    def e2g_stop(self, button):
        os.system("service e2guardian stop")
        stop = builder.get_object("stop")
        stop.set_text("Stopped")
    def e2g_reload(self, button):
        os.system("service e2guardian reload")
        reloader = builder.get_object("reload")
        reloader.set_text("Reloaded")
    def edit_domains(self, button):
        os.system("gedit /etc/e2guardian/lists/blacklists/whitelist/domains")
    def edit_urls(self, button):
        os.system("gedit /etc/e2guardian/lists/blacklists/whitelist/urls")
    def launch_squid_cp(self, button):
        os.system("squidcp")
#get glade file
gladefile = os.path.split(__file__)[0] + '/e2gcp.glade'

#builds GUI for app
builder = Gtk.Builder()
builder.add_from_file(gladefile)
builder.connect_signals(Handler())

window = builder.get_object("e2gcp")
window.show_all()


Gtk.main()
